language: rust
matrix:
  fast_finish: true
  allow_failure:
      - rust: nightly
  include:
    # =====================================================================
    # Stable
    # =====================================================================
    - rust: stable
      name: netlink-sys
      script:
        - cd netlink-sys
        - cargo test
        - cargo test --features mio_support
        - cargo test --features tokio_support

    - rust: stable
      name: netlink-packet
      script:
        - cd netlink-packet
        - cargo test --features audit
        - cargo test --features rtnetlink
        - cargo test --features sock_diag

    - rust: stable
      name: netlink-proto
      script:
        - cd netlink-proto
        - cargo test --features audit
        - cargo test --features rtnetlink
        - cargo test --features sock_diag

    - rust: stable
      name: rtnetlink
      script:
        - cd rtnetlink
        - cargo test

    - rust: stable
      name: audit
      script:
        - cd audit
        - cargo test

    # =====================================================================
    # Nightly
    # =====================================================================

    - rust: nightly
      name: nightly netlink-sys
      before_script:
        - rustup component add clippy-preview
      script:
          - cargo test -Z package-features --package netlink-sys
          - cargo test -Z package-features --package netlink-sys --features mio_support
          - cargo test -Z package-features --package netlink-sys --features tokio_support
          - cargo clippy

    - rust: nightly
      name: nightly netlink-packet
      before_script:
        - rustup component add clippy-preview
      script:
          - cargo test -Z package-features --package netlink-packet --features audit
          - cargo test -Z package-features --package netlink-packet --features rtnetlink
          - cargo test -Z package-features --package netlink-packet --features sock_diag
          - cargo clippy

    - rust: nightly
      name: nightly netlink-proto
      before_script:
        - rustup component add clippy-preview
      script:
          - cargo test -Z package-features --package netlink-proto --features audit
          - cargo test -Z package-features --package netlink-proto --features rtnetlink
          - cargo test -Z package-features --package netlink-proto --features sock_diag
          - cargo clippy

    - rust: nightly
      name: nightly netlink-proto
      before_script:
        - rustup component add clippy-preview
      script:
          - cargo test -Z package-features --package rtnetlink
          - cargo test -Z package-features --package audit
          - cargo test -Z package-features --package sock_diag
          - cargo clippy

    - rust: nightly
      name: rustfmt
      before_script:
        - rustup component add rustfmt-preview
      script:
          - cargo fmt --all -- --check
