[package]
name = "netlink"
version = "0.1.0"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]

[dependencies]
byteorder = "1.2.2"
libc = "0.2.40"
mio = "0.6.14"
tokio-io = "0.1.6"
tokio-reactor = "0.1.1"
futures = "0.1"

# This was used to generate the constants the /usr/include/linux header files.
# I keep it here in case I need to regenerate them.
# [build-dependencies]
# bindgen = "0.36.1"

[dev-dependencies]
lazy_static = "1.0"
