[package]
name = "netlink"
version = "0.1.0"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]

[dependencies]
byteorder = "1.2.2"
libc = "0.2.40"
mio = "0.6.14"
tokio-io = "0.1.6"
tokio-reactor = "0.1.1"
futures = "0.1"

[build-dependencies]
bindgen = "0.36.1"
